# Generated by Django 5.2 on 2025-04-29 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "installment_number",
                    models.PositiveIntegerField(verbose_name="Número da Parcela"),
                ),
                (
                    "installment_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor da Parcela"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Data de Vencimento")),
                ("is_paid", models.BooleanField(default=False, verbose_name="Pago")),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="expenses.expense",
                        verbose_name="Despesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcela",
                "verbose_name_plural": "Parcelas",
                "ordering": ["due_date"],
                "unique_together": {("expense", "installment_number")},
            },
        ),
    ]
