# Generated by Django 5.2 on 2025-06-06 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dividend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ativo",
            old_name="name",
            new_name="codigo",
        ),
        migrations.AddField(
            model_name="ativo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ACAO", "Ação"),
                    ("FII", "Fundo Imobiliário"),
                    ("BDR", "BDR"),
                    ("ETF", "ETF"),
                ],
                default="ACAO",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="itemdividendo",
            name="data_recebimento",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 6, 6, 18, 24, 1, 912084, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="carddividendomes",
            name="mes",
            field=models.IntegerField(),
        ),
    ]
