# Generated by Django 5.2 on 2025-06-20 00:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dividend", "0002_rename_name_ativo_codigo_ativo_tipo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ativo",
            unique_together={("codigo", "user")},
        ),
    ]
